version: '3'

services:

  dev:
    container_name: nodejs-recipes-api
    build: '.'
    command: 'yarn dev:server'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    user: root

  test:
    container_name: nodejs-recipes-api-test
    build: '.'
    command: yarn test
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3334:3334'
    user: root